site_name: Go Observability
site_description: Documentation for the go-observability library
repo_name: ecoma-io/go-observability
repo_url: https://github.com/ecoma-io/go-observability
site_author: ecoma-io
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    primary: "blue"
    accent: "indigo"
  features:
    - navigation.instant
    - navigation.sections
    - toc.integrate
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Configuration: configuration.md
  - Logging: logging.md
  - OpenTelemetry: otel.md
  - Gin Middleware: gin-middleware.md
  - gRPC: grpc.md
  - Audit: audit.md
  - Examples: examples.md
plugins:
  - search
  - mermaid2
  - mkdocstrings
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
